source "http://rubygems.org"

# iruby dependencies
gem 'rbczmq'
gem 'ffi-rzmq'
gem 'iruby'

# fetch from the github master branch
gem 'daru', :git => 'https://github.com/SciRuby/daru.git'

gem "nyaplot", git: 'https://github.com/SciRuby/nyaplot.git'

gem 'data_tables', git: 'https://github.com/Shekharrajak/data_tables.git'

# daru-view
gemspec  :path => '../../'

# used in tutorials :
# Nyaplot | Creating Visualizations with DataFrame  | from daru examples
gem 'distribution'
